-- MS-002 canonical business schema.
-- The preceding 20260620000000_initial_empty migration is intentionally kept empty.

CREATE TABLE feeds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL UNIQUE,
  title text,
  active boolean,
  subscriber_count integer NOT NULL DEFAULT 0,
  etag text,
  last_modified text,
  last_checked_at timestamptz,
  last_new_entry_at timestamptz,
  last_http_status smallint,
  error_count integer,
  next_check_at timestamptz,
  created_at timestamptz,
  CONSTRAINT feeds_etag_length_check
    CHECK (etag IS NULL OR char_length(etag) <= 1024),
  CONSTRAINT feeds_last_modified_length_check
    CHECK (last_modified IS NULL OR char_length(last_modified) <= 256),
  CONSTRAINT feeds_title_length_check
    CHECK (title IS NULL OR char_length(btrim(title)) BETWEEN 1 AND 300),
  CONSTRAINT feeds_subscriber_count_non_negative
    CHECK (subscriber_count >= 0)
);

CREATE TABLE entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feed_id bigint NOT NULL,
  guid text NOT NULL,
  url text NOT NULL,
  title text NOT NULL,
  summary text,
  images jsonb,
  videos jsonb,
  tags jsonb,
  author text,
  meta jsonb,
  published_at timestamptz,
  first_seen_at timestamptz NOT NULL,
  effective_at timestamptz GENERATED ALWAYS AS (COALESCE(published_at, first_seen_at)) STORED,
  detail_extraction_status text NOT NULL,
  detail_extraction_error_code text,
  detail_extraction_attempted_at timestamptz,
  detail_extraction_finalized_at timestamptz NOT NULL,
  has_detail boolean NOT NULL DEFAULT false,
  created_at timestamptz,
  CONSTRAINT entries_feed_id_fkey
    FOREIGN KEY (feed_id) REFERENCES feeds(id),
  CONSTRAINT entries_feed_id_guid_key
    UNIQUE (feed_id, guid),
  CONSTRAINT entries_id_feed_id_unique
    UNIQUE (id, feed_id),
  CONSTRAINT entries_detail_extraction_status_check
    CHECK (
      detail_extraction_status IN (
        'ok',
        'timeout',
        'playwright_failed',
        'blocked',
        'empty_content',
        'normalizer_rejected',
        'skipped_budget_exceeded'
      )
    ),
  CONSTRAINT entries_detail_extraction_attempted_at_check
    CHECK (
      (detail_extraction_status = 'skipped_budget_exceeded' AND detail_extraction_attempted_at IS NULL) OR
      (detail_extraction_status <> 'skipped_budget_exceeded' AND detail_extraction_attempted_at IS NOT NULL)
    ),
  CONSTRAINT entries_detail_extraction_error_code_ok_check
    CHECK (detail_extraction_status <> 'ok' OR detail_extraction_error_code IS NULL),
  CONSTRAINT entries_detail_extraction_error_code_length_check
    CHECK (
      detail_extraction_error_code IS NULL OR
      char_length(btrim(detail_extraction_error_code)) BETWEEN 1 AND 100
    ),
  CONSTRAINT entries_detail_extraction_time_order_check
    CHECK (
      detail_extraction_attempted_at IS NULL OR
      detail_extraction_finalized_at >= detail_extraction_attempted_at
    ),
  CONSTRAINT entries_guid_length_check
    CHECK (char_length(btrim(guid)) BETWEEN 1 AND 2048),
  CONSTRAINT entries_url_length_check
    CHECK (char_length(btrim(url)) BETWEEN 1 AND 2048),
  CONSTRAINT entries_title_length_check
    CHECK (char_length(btrim(title)) BETWEEN 1 AND 500),
  CONSTRAINT entries_summary_length_check
    CHECK (summary IS NULL OR char_length(summary) <= 2000),
  CONSTRAINT entries_author_length_check
    CHECK (author IS NULL OR char_length(author) <= 200)
);

CREATE TABLE entry_details (
  entry_id bigint PRIMARY KEY,
  feed_id bigint NOT NULL,
  effective_at timestamptz NOT NULL,
  detail text NOT NULL,
  detail_length integer,
  created_at timestamptz,
  CONSTRAINT entry_details_detail_length_check
    CHECK (char_length(detail) <= 30000),
  CONSTRAINT entry_details_entry_feed_match_fk
    FOREIGN KEY (entry_id, feed_id)
    REFERENCES entries(id, feed_id)
    ON DELETE CASCADE
);

CREATE TABLE site_feeds (
  site_client_id text NOT NULL,
  feed_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT site_feeds_pkey
    PRIMARY KEY (site_client_id, feed_id),
  CONSTRAINT site_feeds_feed_id_fkey
    FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE RESTRICT
);

CREATE TABLE agent_feed_check_events (
  check_id text PRIMARY KEY,
  feed_id bigint,
  checked_at timestamptz,
  http_status smallint,
  outcome text NOT NULL,
  entries_submitted_count integer NOT NULL DEFAULT 0,
  entries_saved_count integer NOT NULL DEFAULT 0,
  error_code text,
  tier_attempted smallint NOT NULL,
  response_etag text,
  response_last_modified text,
  feed_title text,
  created_at timestamptz,
  CONSTRAINT agent_feed_check_events_response_etag_length_check
    CHECK (response_etag IS NULL OR char_length(response_etag) <= 1024),
  CONSTRAINT agent_feed_check_events_response_last_modified_length_check
    CHECK (response_last_modified IS NULL OR char_length(response_last_modified) <= 256),
  CONSTRAINT agent_feed_check_events_outcome_check
    CHECK (outcome IN ('not_modified', 'no_new_entries', 'fetch_error', 'entries_found')),
  CONSTRAINT agent_feed_check_events_error_code_by_outcome_check
    CHECK (
      (outcome = 'fetch_error' AND error_code IS NOT NULL AND char_length(btrim(error_code)) BETWEEN 1 AND 100)
      OR
      (outcome <> 'fetch_error' AND error_code IS NULL)
    ),
  CONSTRAINT agent_feed_check_events_http_status_by_outcome_check
    CHECK (
      (outcome IN ('entries_found', 'no_new_entries') AND http_status = 200)
      OR
      (outcome = 'not_modified' AND http_status = 304)
      OR
      (outcome = 'fetch_error' AND http_status <> 304)
    ),
  CONSTRAINT agent_feed_check_events_tier_attempted_check
    CHECK (tier_attempted IN (1, 2)),
  CONSTRAINT agent_feed_check_events_entry_counts_by_outcome_check
    CHECK (
      (
        outcome = 'entries_found'
        AND entries_submitted_count > 0
        AND entries_saved_count >= 0
        AND entries_saved_count <= entries_submitted_count
      )
      OR
      (
        outcome <> 'entries_found'
        AND entries_submitted_count = 0
        AND entries_saved_count = 0
      )
    ),
  CONSTRAINT agent_feed_check_events_feed_title_length_check
    CHECK (feed_title IS NULL OR char_length(btrim(feed_title)) BETWEEN 1 AND 300),
  CONSTRAINT agent_feed_check_events_feed_title_outcome_check
    CHECK (feed_title IS NULL OR outcome IN ('entries_found', 'no_new_entries'))
);

CREATE TABLE agent_runtime_status (
  agent_id text PRIMARY KEY,
  status text NOT NULL,
  last_heartbeat_sent_at timestamptz NOT NULL,
  last_heartbeat_received_at timestamptz NOT NULL,
  feeds_processed integer NOT NULL,
  errors_count integer NOT NULL,
  stale_check_results_dropped integer NOT NULL,
  stale_entries_dropped integer NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX entries_feed_effective
  ON entries(feed_id, effective_at DESC, id DESC);

CREATE INDEX entries_created
  ON entries(created_at);

CREATE INDEX feeds_due
  ON feeds(next_check_at ASC, id ASC)
  WHERE active = true AND subscriber_count > 0;

CREATE INDEX entry_details_created
  ON entry_details(created_at);

CREATE INDEX entry_details_feed_effective
  ON entry_details(feed_id, effective_at DESC, entry_id DESC);

CREATE INDEX agent_feed_check_events_created
  ON agent_feed_check_events(created_at);

CREATE INDEX site_feeds_feed_id
  ON site_feeds(feed_id);
